replicaCount: 1

image:
  repository: bitwardenrs/server
  tag: latest 
  pullPolicy: IfNotPresent

env:
  SIGNUPS_ALLOWED: false
  INVITATIONS_ALLOWED: true
  ADMIN_TOKEN: ""
  SERVER_ADMIN_EMAIL: ""
  DOMAIN: ""
  SMTP_HOST: "smtp.gmail.com"
  SMTP_FROM: ""
  SMTP_PORT: 587
  SMTP_SSL: true
  SMTP_USERNAME: ""
  SMTP_PASSWORD: ""

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  loadBalancerIP:

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - ""
  tls:
    - secretName: bitwarden-tls
      hosts:
        - ""

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
podAnnotations: {}
deploymentAnnotations: {}

## Persist data to a persitent volume
persistence:
  enabled: true 
  existingClaim: "bitwarden"
