
replicaCount: 1

image:
  repository: linuxserver/jackett
  tag: latest
  pullPolicy: IfNotPresent

env:
  - name: TZ
    value: Europe/Paris
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

volumes:
  - name: media-apps
    persistentVolumeClaim:
      claimName: media-apps
  - name: media-data
    persistentVolumeClaim:
      claimName: media-data

volumeMounts:
  - name: media-apps
    mountPath: "/config"
    subPath: "configs/jackett"
  - name: media-data
    mountPath: "/downloads"
    subPath: "downloads/jackett"

resources:
  requests:
    memory: 128Mi
    cpu: 0.1
  limits:
    memory: 256Mi
    cpu: 0.5

securityContext:
  capabilities: # Needed for VPN
    add:
      - NET_ADMIN

nodeSelector: {}

tolerations: []

affinity: {}

