
replicaCount: 1

image:
  repository: linuxserver/radarr
  tag: latest
  pullPolicy: IfNotPresent

env:
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

volumes:
  - name: media
    persistentVolumeClaim:
      claimName: media

volumeMounts:
  - name: media
    mountPath: "/config"
    subPath: "configs/radarr"
  - name: media
    mountPath: "/downloads/transmission"
    subPath: "downloads/transmission"
  - name: media
    mountPath: "/movies"
    subPath: "medias/movies"

resources:
  requests:
    memory: 128Mi
    cpu: 0.1
  limits:
    memory: 256Mi
    cpu: 0.5

nodeSelector: {}

tolerations: []

affinity: {}

