#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  repository: vaultwarden/server
  pullPolicy: IfNotPresent
  tag: 1.22.2

strategy:
  type: Recreate

env:
  DATA_FOLDER: "config"

service:
  main:
    ports:
      http:
        port: 80
      websocket:
        enabled: true
        port: 3012

ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: ""
        paths:
          - path: /
    tls:
      - secretName: bitwarden-tls
        hosts:
          - ""

persistence:
  config:
    enabled: true
    existingClaim: "bitwarden"
